### ISSUE TITLE
Submission to official phpBB extensions database

### ISSUE THREAD

**Issue by Zoddo** [ForumHulp/emailonbirthday#1]
Hi!

I think that it will be a good idea to translate this extension in english and submit it to the [phpBB.com extensions database](https://www.phpbb.com/extensions/) (after fixing [EPV](https://www.phpbb.com/extensions/epv/) issues).

PS : If this extension is translated in english, I can translate it to french.

**Comment by Galixte** [comment]
Hi,

it’s ready @Zoddo. you can close this issue. ;)

**Comment by Zoddo** [comment]
Hum ... no, there are EPV issues

**Comment by Galixte** [comment]
sorry ^_^

@ForumHulp, please could you take a look ?

**Comment by Galixte** [comment]
@Zoddo, je pense que c’est bon, non ?

**Comment by ForumHulp** [comment]
???

**Comment by Galixte** [comment]
I ask to Zoddo if it’s ok for him ? https://github.com/ForumHulp/emailonbirthday/commit/85f61057b9058659d49dae5b231e041a303febae#diff-354f30a63fb0907d4ad57269548329e3

**Comment by ForumHulp** [comment]
Who is zoddo?

Greetz

 http://forumhulp.com/ fhcom
Webhosting, Custom MODs, Technisch beheer, MOD installaties, Webdesign  en website ontwikkeling

Van: Raphaël M. [mailto:notifications@github.com] 
Verzonden: vrijdag 3 juli 2015 9:09
Aan: ForumHulp/emailonbirthday
CC: Forumhulp.com
Onderwerp: Re: [emailonbirthday] Submission to official phpBB extensions database (#1)

I ask to Zoddo if it’s ok for him ?  https://github.com/ForumHulp/emailonbirthday/commit/85f61057b9058659d49dae5b231e041a303febae#diff-354f30a63fb0907d4ad57269548329e3 85f6105#diff-354f30a63fb0907d4ad57269548329e3

**Comment by Zoddo** [comment]
> Who is zoddo?

Me :)

I think that this extension can be accepted in the Extension Database, now :)

**Comment by ForumHulp** [comment]
Hi Zoddo,

It errored on the last commit, first find the problem

**Comment by Zoddo** [comment]
> It errored on the last commit

What do you mean?

**Comment by ForumHulp** [comment]
It's waiting for validation
