### ISSUE TITLE
E-mails aren’t sent

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/emailonbirthday#10]
Hi @ForumHulp,

it seems the birthday emails are not sent to user which have a birthday.

Is only for new registered users after installation of this extension or for all users already registered ?

Could you take a look ?

**Comment by ForumHulp** [comment]
If you install it today it set timestamp of today for emails send for all users.
So the first birthday-email send will be after a half year for users who have filled in their birthday.

**Comment by Galixte** [comment]
My board users and me have to waiting a half YEAR to recevied the first birthday email ?

And for new registered users (after installation) ?

@Zoddo, tu comprends quelque chose ?

**Comment by Galixte** [comment]
Fixed here: https://github.com/ForumHulp/emailonbirthday/commit/c3879ff02e0f1f88becc481b84c1f40e9e0e6f29.
