### ISSUE TITLE
Where is this extension ? forumhulp\htmlemail

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/emailonbirthday#11]
Hi @ForumHulp,

where i can find the extension: forumhulp\htmlemail ?

**Comment by ForumHulp** [comment]
It’s not online, sen mailaddress and I will send it to you

Van: Raphaël M. [mailto:notifications@github.com] 
Verzonden: vrijdag 18 september 2015 12:20
Aan: ForumHulp/emailonbirthday
CC: Forumhulp.com
Onderwerp: [emailonbirthday] Where is this extension ? forumhulp\htmlemail (#11)

Hi @ForumHulp https://github.com/ForumHulp ,

where i can find the extension: forumhulp\htmlemail ?

**Comment by Galixte** [comment]
Ok, thanks, contact at galixte dot com.

**Comment by Galixte** [comment]
I got it thanks to ForumHulp. This extension will be published later on GitHub.
