### ISSUE TITLE
Precisions for a language key

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/emailonbirthday#12]
Hi @ForumHulp,

about this language key:

```
    'E_MAIL_ON_BIRTHDAY_NOTICE'     => '<div class="attach-image"><p>There are no settings for this extension. To use this function you have to switch html to on in your application. Use $messenger->use_html(true); to activate html email.</p></div>',
```

When it said: “There are no settings for this extension”, you’re talking about the extension: forumhulp\htmlemail ?

When it said: “To use this function you have to switch html to on in your application”, “your application” is about phpBB, PHP, Mail server ?

Finally, when it said: “Use $messenger->use_html(true); to activate html email”, in which file ? Do you have an example of using ?

**Comment by ForumHulp** [comment]
Yes it’s double up, I will change the text

Van: Raphaël M. [mailto:notifications@github.com] 
Verzonden: vrijdag 18 september 2015 12:28
Aan: ForumHulp/emailonbirthday
CC: Forumhulp.com
Onderwerp: [emailonbirthday] To which one is destinated this language key (#12)

Hi @ForumHulp https://github.com/ForumHulp ,

about this language key:
``` 'E_MAIL_ON_BIRTHDAY_NOTICE' => '

There are no settings for this extension. To use this function you have to switch html to on in your application. Use $messenger->use_html(true); to activate html email.

',

When it said: “There are no settings for this extension”, you’re talking about the extension: forumhulp\htmlemail ?

When it said: “To use this function you have to switch html to on in your application”, “your application” is about phpBB, PHP, Mail server ?

Finally, when it said: “Use $messenger->use_html(true); to activate html email”, in which file ? Do you have an example of using ?

—
Reply to this email directly or view it on GitHub https://github.com/ForumHulp/emailonbirthday/issues/12 .  https://github.com/notifications/beacon/AGaIJmrBr-HwIfEcHJqe0DrMNOfQTF58ks5oy96TgaJpZM4F_xnM.gif

**Comment by Galixte** [comment]
I don’t understand your answer, i have updated my first post.

**Comment by ForumHulp** [comment]
Maybe the message is more clear now.

After waiting for 3 month, cleaning up text according to phpBB and again denied I stop with sending in for validating simply because it takes to much time and is about nothing. They are testing a version which is already outdated again and again. It's not about security anymore. There are many ways to skin a cat.

**Comment by Galixte** [comment]
Since your last commit, the message doesn’t displays the path to configure this extendion, instead i can read this: …%1$s » %2$s » %3$s…

**Comment by ForumHulp** [comment]
Stupid from me, uploaded

**Comment by Galixte** [comment]
Thanks it works !
