### ISSUE TITLE
Age isn’t completed in email

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/emailonbirthday#15]
Hi @ForumHulp,

if the user concerned by his birthday has 54 years old. The email will be : 

```
Bonjour cobaye,

Toutes nos félicitations pour votre -quatrième anniversaire. L’équipe du
forum Communauté EzCom espère que vous passerez une excellente journée !


En un pareil évènement, nous vous souhaitons que du bonheur et la santé,


-- 
Cordialement, l'équipe du forum EzCom.
```

So, the problem is in french, for 54 years old, it should be : `cinquante-quatrième` but now it’s only `-quatrième`, missing the 5 of ten. To translate you:
- `cinquante` = `fifty`
- `quatre` = `four`
- and because it’s an age, in French we use the adds `ième` at the end of the digit, with this line: `ord:(.*)e \1ième    # quatre etc.`.

In `fr.num` file, it’s this next line which is important for this situation: `(\d)(\d) $(\10)-$2`.

Your script doesn’t display or take in consideration the ten in birthday.

**Comment by Galixte** [comment]
Hi @ForumHulp,

please, can i have an answer ?

**Comment by ForumHulp** [comment]
I mailed the author but didn't got a answer yet Galixte

**Comment by Galixte** [comment]
Hi @ForumHulp,

the author of what, please ?
