### ISSUE TITLE
Idea: Add PM and Notification

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/emailonbirthday#16]
Why not PM and/or Notification too on birthday? The admin would choose the mode: Email / PM / Notification

**Comment by ForumHulp** [comment]
Nice idea, next version, shouldn't the user decide how to be noted?

**Comment by Leinad4Mind** [comment]
Well, I guess that all users when do a birthday like to receive happy brithdays, so I would say that he will not want to change how to be noted. I guess it does more sense to be the admin to choose. But, if you want to do an extension to like everyone, then you could do a way for admins selecting a default value for all users and the ability for users change that via UCP just in case. And if possible a disable/enable option on ACP about the user being able to change the default settings.

**Comment by ForumHulp** [comment]
Goo idea, first Classifieds finishing
