### ISSUE TITLE
phpBB 3.2

### ISSUE THREAD

**Issue by Aurelienazerty** [ForumHulp/emailonbirthday#17]
As phpBB 3.2 change the notification system, this extension is not compatible :` Argument 1 passed to phpbb\notification\type\base::__construct() must implement interface phpbb\db\driver\driver_interface, instance of phpbb\user_loader given in [..]/phpbb/notification/type/base.php on line 87`

**Comment by ForumHulp** [comment]
As soon as I have time.

A lot of work for the 3.2 version and his problems

 

 

Greetz

 

 

Van: Aurelienazerty [mailto:notifications@github.com] 
Verzonden: dinsdag 10 januari 2017 16:27
Aan: ForumHulp/emailonbirthday <emailonbirthday@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/emailonbirthday] phpBB 3.2 (#17)

 

As phpBB 3.2 change the notification system, this extension is not compatible :Argument 1 passed to phpbb\notification\type\base::__construct() must implement interface phpbb\db\driver\driver_interface, instance of phpbb\user_loader given in [..]/phpbb/notification/type/base.php on line 87

**Comment by wads24** [comment]
Is out now compatible with 3.2.2 PHPBB
