### ISSUE TITLE
Cannot install this extension

### ISSUE THREAD

**Issue by thefactor82** [ForumHulp/emailonbirthday#19]
On a Phpbb3.2 forum, I've tried to install tis extension but when I activate it, it says

Forumhulp helper application does not exist!
Download forumhulp/helper and copy the helper folder to your forumhulp extension folder.

**Comment by Galixte** [comment]
Hi @thefactor82,

yes before installing an extension from this author you have to install this extension: https://github.com/ForumHulp/helper. ;)

**Comment by thefactor82** [comment]
Hi,Yes, I guessed this thing only after opening the issue, so I've closed it.Sorry about that!
TheFactor82




----Messaggio originale----

Da: "Raphaël M." <notifications@github.com>

Data: 29-ago-2017 8.51

A: "ForumHulp/emailonbirthday"<emailonbirthday@noreply.github.com>

Cc: "thefactor82"<mam1982@virgilio.it>, "Mention"<mention@noreply.github.com>

Ogg: Re: [ForumHulp/emailonbirthday] Cannot install this extension (#19)




Hi @thefactor82,

yes before installing an extension from this author you have to install this extension: https://github.com/ForumHulp/helper. ;)

**Comment by Galixte** [comment]
Never mind! This will help future visitors. ;)

@ForumHulp, it could be usefull to add a notice about to install HELPER extension before each of your extensions, in the README files from these.
